### this file exists because of a bug which prevents
### "python -m unittest" from discovering tests inside
### packages lacking a __init__.py file; check this
### issue for more info:
### https://github.com/python/cpython/pull/11364
###
### Once the bug is fixed, this file can be removed, since
### it has no other purpose.
